# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # Image preparation
      - name: Build my Docker image
        run: docker build -t testask .

      # Runs a set of commands using the runners shell
      # Check if curl version output is correct
      - name: Check if curl version output is correct
        run: |
          curl_ver=$(curl -s https://api.github.com/repos/curl/curl/releases/latest | grep -m1 -oP '(?<="name": ")[0-9.]+')
          docker run -t --rm testask --version | grep $curl_ver

      - name: Check if curl fetches an URL correctly
        run: |
          url="ifconfig.me/ip"
          my_ip=$(curl -s $url)
          docker run -t testask $url | grep -q $my_ip
